---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.env }}
  labels:
    name: {{ .Values.env }}


---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.env }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
