apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-ingress
  namespace: {{ $.Values.env }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ $.Values.externalHost }}
      http:
        paths:
          - backend:
              serviceName: nginx-service
              servicePort: 8080
