apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: task-pv-claim
    namespace: {{ $.Values.env }}
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 9Gi