---
apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: {{ $.Values.env }}
  labels:
    app: php
spec:
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: http-php

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ $.Values.env }}
  labels:
    app: http-php
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: http-php
